Merge private & public repositories.
JuliaInv/MaxwellFrequency pull request #2
Opened 2017-03-09 23:05 UTC by dwfmarchant

Merges the changes that were made on the master branches of the private and the public repositories.    Adds a CSEM example that runs on a tensor mesh.

2017-03-10 01:12 UTC, Pbellive requested changes
Hi Dave,
                 Thanks a lot for getting this ready. I'd like to make sure this runs with the latest updates to JOcTree. The only thing I noticed was one spot where the call signature for `getEdgeIntegralOfPolygonalChain` had to be changed in the OcTree inversion examples. If you could fix that then I'll merge these changes. Thanks

2017-03-10 01:12 UTC, Pbellive commented on inversion-examples/testCSEMSingleMesh/runMaxFreqUBCInversionSingleMesh.jl
> +	Receivers[:,i] = complex(getEdgeIntegralOfPolygonalChain(M,rcv[i],nEx,nEy,nEz,normalize=true))
Now that Roman's JOcTree changes have been merged, could you update the `getEdgeIntegralOfPolygonalChain` calls to the new signature before merging? Thanks.

2017-03-10 02:09 UTC, dwfmarchant commented
I think that I did that already but I'll check tomorrow.


On Thu, Mar 9, 2017 at 5:12 PM Patrick Belliveau <notifications@github.com>
wrote:

> *@Pbellive* requested changes on this pull request.
>
> Hi Dave,
> Thanks a lot for getting this ready. I'd like to make sure this runs with
> the latest updates to JOcTree. The only thing I noticed was one spot where
> the call signature for getEdgeIntegralOfPolygonalChain had to be changed
> in the OcTree inversion examples. If you could fix that then I'll merge
> these changes. Thanks
> ------------------------------
>
> In
> inversion-examples/testCSEMSingleMesh/runMaxFreqUBCInversionSingleMesh.jl
> <https://github.com/JuliaInv/MaxwellFrequency/pull/2#discussion_r105309049>
> :
>
> >  end
>
>  # receivers
>  Receivers = spzeros(Complex128, sum(M.ne), length(rcv))
>  for i = 1:length(rcv)
> -        ply            = [rcv[i][:,1:2] zSurf*ones(size(rcv[i],1))]
> -        if sum(ply[1,:]-ply[2,:]) == 0.0
> -          ply[1,3] = zSurf-10
> -          ply[2,3] = zSurf+10
> -        end
> -	Receivers[:,i] = complex(getEdgeIntegralOfPolygonalChain(M,ply,normalize=true))
> +	Receivers[:,i] = complex(getEdgeIntegralOfPolygonalChain(M,rcv[i],nEx,nEy,nEz,normalize=true))
>
> Now that Roman's JOcTree changes have been merged, could you update the
> getEdgeIntegralOfPolygonalChain calls to the new signature before
> merging? Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JuliaInv/MaxwellFrequency/pull/2#pullrequestreview-26184105>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFtL3TkWjVLBb69-4EkV_TVrRgDEl7dDks5rkKN0gaJpZM4MYwNe>
> .
>

2017-03-14 21:17 UTC, dwfmarchant commented
I think that's everything - I just reran the inversion examples and they all run again.

2017-03-14 21:18 UTC, Pbellive approved these changes

2017-03-14 21:21 UTC, merged

2017-03-14 21:21 UTC, Pbellive commented
Merged. Thanks again Dave.